export const selectors = {
  loadingOverlay: '#loadingOverlay',
  hearts: '#hearts .heart',
  message: '#message',
  newGameBtn: '#newGameBtn',
  overlay: '#overlay',
  overlayVisible: '#overlay.visible',
  modalTitle: '#modalTitle',
  modalText: '#modalText',
  modalBtn: '#modalBtn',
  modalDialog: '#modal',
  modalHighlight: '#modalText .highlight',
  score: '#score',
  letterInput: '#letterInput',
  guessBtn: '#guessBtn',
  wordDisplay: '#wordDisplay',
  wordGroup: '#wordDisplay .word-group',
  letterSlot: '.letter-slot',
  choices: '#choices button',
  characterName: '#characterName',
  characterPhoto: '#characterPhoto',
  backLink: '.back-link',
  gameCard: '.game-card',
  moves: '#moves button',
  playerScore: '#playerScore',
  opponentScore: '#opponentScore',
  opponentPhoto: '#opponentPhoto',
  duelReveal: '#duelReveal',
  opponentName: '#opponentName',
  chatSetup: '#chatSetup',
  chatRoom: '#chatRoom',
  nickname: '#nickname',
  characterSelect: '#characterSelect',
  startChatBtn: '#startChatBtn',
  setupError: '#setupError',
  chatLog: '#chatLog',
  messageInput: '#messageInput',
  sendBtn: '#sendBtn',
  backToSetupBtn: '#backToSetupBtn',
  partnerName: '#partnerName',
  chatUserText: '.chat-message--user .chat-message-text',
  chatCharacterText: '.chat-message--character .chat-message-text',
};
