export const selectors = {
  loadingOverlay: '#loadingOverlay',
  hearts: '#hearts .heart',
  message: '#message',
  newGameBtn: '#newGameBtn',
  overlay: '#overlay',
  overlayVisible: '#overlay.visible',
  modalTitle: '#modalTitle',
  modalText: '#modalText',
  modalBtn: '#modalBtn',
  modalDialog: '#modal',
  modalHighlight: '#modalText .highlight',
  score: '#score',
  letterInput: '#letterInput',
  guessBtn: '#guessBtn',
  wordDisplay: '#wordDisplay',
  wordGroup: '#wordDisplay .word-group',
  letterSlot: '.letter-slot',
  choices: '#choices button',
  characterName: '#characterName',
  characterPhoto: '#characterPhoto',
  backLink: '.back-link',
  gameCard: '.game-card',
};
